# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
# profiles:
#   `skip`: Skip the service
#   `build`: Build the service

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: ClickHouse
    ports: ["8123:8123"]
    profiles: ["skip"]

  mssql:
    build: { context: ".", dockerfile: "dockerfiles/mssql.Dockerfile" }
    image: sql-learning-materials/mssql:2022
    container_name: SQL-Server
    ports: ["1433:1433"]
    profiles: ["build"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer

  mysql:
    image: mysql:8.4.2
    container_name: MySQL
    ports: ["3306:3306"]
    profiles: ["skip"]
    environment:
      MYSQL_ROOT_PASSWORD: Test@12345

  postgres:
    build: { context: ".", dockerfile: "dockerfiles/postgres.Dockerfile" }
    image: sql-learning-materials/postgres:16.2
    container_name: PostgreSQL
    ports: ["5432:5432"]
    profiles: ["build"]
    environment:
      POSTGRES_PASSWORD: Test@12345
      POSTGRES_USER: postgres

  metabase:
    image: metabase/metabase:latest
    container_name: Metabase
    hostname: metabase
    ports: ["3000:3000"] # http://localhost:3000/
    profiles: ["skip"]
    depends_on: ["mssql", "postgres"]
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - type: bind
        source: ./dockerfiles/metabase-data
        target: /metabase-data/
