---
services:
  mssql:
    build:
      context: .
      dockerfile: dockerfiles/mssql.Dockerfile
    image: mssql
    container_name: SQL-Server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports: ["1433:1433"]

  postgres:
    build:
      context: .
      dockerfile: dockerfiles/postgres.Dockerfile
    image: postgresql
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: Test@12345
      POSTGRES_USER: postgres
    ports: ["5432:5432"]

  metabase:
    image: metabase/metabase:latest
    container_name: Metabase
    hostname: metabase
    volumes:
      - /metabase-data:/metabase-data
    ports: ["3000:3000"]
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on: [mssql, postgres]
