# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
# profiles:
#   `skip`: Skip the service
#   `build`: Build the service

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12
    container_name: ClickHouse
    ports: ["8123:8123"]
    profiles: ["skip"]
    environment:
      CLICKHOUSE_PASSWORD: Test@12345
      CLICKHOUSE_USER: default
    volumes:
      - &shared-volume
        type: bind
        source: ./dockerfiles/shared
        target: /shared/

  mssql:
    build: { context: ".", dockerfile: "dockerfiles/mssql.Dockerfile" }
    image: sql-learning-materials/mssql:2025
    container_name: SQL-Server
    ports: ["1433:1433"]
    profiles: ["build"]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    volumes: [*shared-volume]

  mysql:
    image: mysql:8.4.2
    container_name: MySQL
    ports: ["3306:3306"]
    profiles: ["skip"]
    environment:
      MYSQL_ROOT_PASSWORD: Test@12345
    volumes: [*shared-volume]

  postgres:
    build: { context: ".", dockerfile: "dockerfiles/postgres.Dockerfile" }
    image: sql-learning-materials/postgres:18.4
    container_name: PostgreSQL
    ports: ["5432:5432"]
    profiles: ["build"]
    environment:
      POSTGRES_PASSWORD: Test@12345
      POSTGRES_USER: postgres
    volumes: [*shared-volume]
